### ISSUE TITLE
Alternate solutions if the GITHUB_ vars do not exist

### ISSUE THREAD

**Issue by jeffalder** [gradle/github-dependency-graph-gradle-plugin#34]
I know this is designed for a GitHub Actions environment, but I'm curious if we can modify the configuration slightly for other environments. 

Today, this plugin will cause a build failure if it's applied without all its expected configuration. I've implemented this as a temporary workaround:
```groovy
if (System.getenv("GITHUB_WORKSPACE") != null
        && System.getenv("GITHUB_REF") != null
        && System.getenv("GITHUB_SHA") != null
        && System.getenv("GITHUB_JOB") != null
        && System.getenv("GITHUB_RUN_NUMBER") != null) {
    apply plugin: GitHubDependencySubmissionPlugin
}
```

But this is fairly annoying to check, and it can get out-of-date. I'd like to propose 2 alternatives if the variables do not have values:

1. Inject known placeholders, such as the name of the variable, into the JSON.
2. Emit a warning message, don't apply anything, and therefore don't generate the JSON.

Note: I'm willing to PR this but I want to make sure I'm doing what the maintainers would accept.

**Comment by JLLeitschuh** [comment]
I think I'd rather see an `GitHubDependencySubmissionPluginOptional` that applies the `GitHubDependencySubmissionPlugin` if those variables are present. That way, if a user wants the guarantee that the plugin will work, or fail, then they can apply the `GitHubDependencySubmissionPlugin`, but if they want flexibility, they could apply the `GitHubDependencySubmissionPluginOptional` version. Thoughts?

**Comment by sschuberth** [comment]
In any case I'd like to be able to use the plugin locally like

    ./gradlew -p plugins/package-managers/gradle/src/funTest/assets/projects/synthetic/gradle-library -I ~/Downloads/github-dependency-graph-gradle-plugin.init.gradle GitHubDependencyGraphPlugin_generateDependencyGraph

without the need to specify any `GITHUB_` environment variables. Maybe these could simply be set to dummy default values if the `GITHUB_ACTION` environment variable is not set?

**Comment by bigdaz** [comment]
I'm not sure that dummy default values make sense for all variable, since several of them form an integral part of the dependency snapshot to be submitted. Unfortunately there are many aspects of the GitHub Dependency Graph snapshot that are not very well documented and it's not clear how they are currently being used, or how they will be used in the future.

I've documented the required environment variables for the most recent plugin release here: https://github.com/gradle/github-dependency-graph-gradle-plugin#required-environment-variables. Of these, the GITHUB_DEPENDENCY_GRAPH_JOB_CORRELATOR is vital, since it is used by GitHub to determine whether a particular dependency snapshot should replace a previous one.

The others I'm not so sure about. 
- `GITHUB_DEPENDENCY_GRAPH_JOB_ID`: the `gradle-build-action` will default this to the `GITHUB_RUN_ID`, but it's not clear how it's used.
- We could almost certainly determine the `GITHUB_SHA` and `GITHUB_REF` values locally
- The `GITHUB_WORKSPACE` is only used to determine the relative path to the build file: this could safely default to the project root directory.

**Comment by bigdaz** [comment]
> In any case I'd like to be able to use the plugin locally like
> 
> ```
> ./gradlew -p plugins/package-managers/gradle/src/funTest/assets/projects/synthetic/gradle-library -I ~/Downloads/github-dependency-graph-gradle-plugin.init.gradle GitHubDependencyGraphPlugin_generateDependencyGraph
> ```
> 
> without the need to specify any `GITHUB_` environment variables. Maybe these could simply be set to dummy default values if the `GITHUB_ACTION` environment variable is not set?

How would you use the generated snapshot, assuming that it contained placeholder values that are invalid for the Dependency Submission API?
Would it help if it was easier to set these values, via a plugin extension, system properties, etc?

**Comment by bigdaz** [comment]
> I know this is designed for a GitHub Actions environment, but I'm curious if we can modify the configuration slightly for other environments.

Can you be more specific about your use case? 

The goal is to ensure that the plugin generates a snapshot file that is valid for the [Dependency Submission API](https://docs.github.com/en/rest/dependency-graph/dependency-submission?apiVersion=2022-11-28). 

Do you mostly want to be able to apply the plugin as a no-op when the required data isn't available, or do you have another use case in mind?

**Comment by sschuberth** [comment]
> How would you use the generated snapshot, assuming that it contained placeholder values that are invalid for the Dependency Submission API?

Basically, I'm just interested in *some* JSON output that lists a Gradle project's dependencies (similar to what is being proposed [here](https://github.com/gradle/gradle/pull/25592)) for further processing in Open Source compliance tools ([ORT](https://github.com/oss-review-toolkit/ort) in my case). As such I can easily ignore the dependency-submission-API-relevant bits.

> Would it help if it was easier to set these values, via a plugin extension, system properties, etc?

Not really; if I have to set them at all, I do not actually care whether that's by environment variables or other means.

**Comment by bigdaz** [comment]
@sschuberth I suppose a plugin that didn't have GitHub-specific inputs and generated output in some sort of SBOM format would be the most useful to you?

**Comment by bigdaz** [comment]
> Most established SBOM formats like [SPDX](https://github.com/spdx/spdx-spec) or [CycloneDX](https://github.com/CycloneDX/specification) are a bit cumbersome to handle if you'd like to record deeply technical metadata about dependencies, like the URL to their sources artifact _and_ the location of the VCS repository (maybe even including the relevant sub-path _within_ that repository).
> 
> So I'd also be fine with (or even prefer) a custom JSON / YAML based format that is fully under our control, to add as much details as we'd like, for third parties to consume / convert.

Thanks for the feedback. 
First I want to nail down the GitHub support, but I've been thinking about a separate Dependency Graph plugin that uses the same infrastructure but produces a different report. 
Can you clarify (maybe with an example) the kind of information you'd like to see included?
It's not clear to me exactly what you mean by "the URL to their sources artifact and the location of the VCS repository".

**Comment by sschuberth** [comment]
> I've been thinking about a separate Dependency Graph plugin that uses the same infrastructure but produces a different report.

:+1: on that, as that could / should nicely replace https://github.com/gradle/gradle/issues/21894, and maybe the https://docs.gradle.org/current/userguide/project_report_plugin.html in general, which despite that page saying

> We plan to add much more to the existing reports and create additional ones in future releases of Gradle.

hasn't seen any updates in ages 😉 

> Can you clarify (maybe with an example) the kind of information you'd like to see included?

Sure thing! Here's an [example output](https://github.com/oss-review-toolkit/ort/blob/812d646dba53902aebc1dd681d877ece83b42d75/plugins/package-managers/gradle/src/funTest/assets/projects/synthetic/gradle-library-expected-output-lib.yml#L87-L137) of what metadata [ORT](https://github.com/oss-review-toolkit/ort) captures for the Apache Commons Lang Maven dependency:

```
- id: "Maven:org.apache.commons:commons-lang3:3.5"
  purl: "pkg:maven/org.apache.commons/commons-lang3@3.5"
  authors:
  - "Benedikt Ritter"
  - "Carman Consulting, Inc."
  - "CollabNet, Inc."
  - "Duncan Jones"
  - "Fredrik Westermarck"
  - "Gary D. Gregory"
  - "Henri Yandell"
  - "Joerg Schaible"
  - "Loic Guibert"
  - "Matt Benson"
  - "Niall Pemberton"
  - "Oliver Heger"
  - "Paul Benedict"
  - "Rob Tompkins"
  - "Robert Burrell Donkin"
  - "SITA ATS Ltd"
  - "Steven Caswell"
  - "The Apache Software Foundation"
  declared_licenses:
  - "Apache License, Version 2.0"
  declared_licenses_processed:
    spdx_expression: "Apache-2.0"
    mapped:
      Apache License, Version 2.0: "Apache-2.0"
  description: "Apache Commons Lang, a package of Java utility classes for the\n \
    \ classes that are in java.lang's hierarchy, or are considered to be so\n  standard\
    \ as to justify existence in java.lang."
  homepage_url: "http://commons.apache.org/proper/commons-lang/"
  binary_artifact:
    url: "https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar"
    hash:
      value: "6c6c702c89bfff3cd9e80b04d668c5e190d588c6"
      algorithm: "SHA-1"
  source_artifact:
    url: "https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5-sources.jar"
    hash:
      value: "f7d878153e86a1cdddf6b37850e00a9f8bff726f"
      algorithm: "SHA-1"
  vcs:
    type: "Git"
    url: "http://git-wip-us.apache.org/repos/asf/commons-lang.git"
    revision: "LANG_3_5"
    path: ""
  vcs_processed:
    type: "Git"
    url: "http://git-wip-us.apache.org/repos/asf/commons-lang.git"
    revision: "LANG_3_5"
    path: ""
```

> It's not clear to me exactly what you mean by "the URL to their sources artifact and the location of the VCS repository".

As you can see in the above example, we know that the Maven source code artifact is at https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5-sources.jar, but we *also* know that the real origin of the source code (from where the source artifact was created) is at http://git-wip-us.apache.org/repos/asf/commons-lang.git, Git tag `LANG_3_5`.
