### ISSUE TITLE
Consider excluding `buildSrc` by default.

### ISSUE THREAD

**Issue by big-andy-coates** [gradle/github-dependency-graph-gradle-plugin#61]
From my testing, there seems to be an inconsistency in the way build plugin dependencies are reported, depending on whether they are installed via build scripts under `buildSrc` vs other build scripts.

Plugins applied in scripts under `buildSrc` directory are included in the dependency report generated by this project's plugin, including any dependencies the plugins require

vs

Plugins applied in normal build scripts, i.e. not under `buildSrc` directory,  are not included in the dependency report.

The `dependencies` Gradle task excludes `buildSrc` by default.  Maybe this plugin should also?

Love the work you're doing here!

Andy

**Comment by big-andy-coates** [comment]
For those running into this issue, a workaround when using the `gradle-build-action` is to set the `DEPENDENCY_GRAPH_INCLUDE_PROJECTS` env to explicitly exclude `buildSrc`:

```yaml
      - name: Setup Gradle
        uses: gradle/gradle-build-action@2
        with:
          dependency-graph: generate
      - name: Build
         env:
           DEPENDENCY_GRAPH_INCLUDE_PROJECTS: "^:(?!buildSrc).*"
         run: ./gradlew build
```
